
[Input]
    slab_filename                       = "./slab/OUTCAR"       # path of file containing the slab atomic coordinates. The list of supported file types can be found on ASE website
    molecule_filename                   = "./mol/OUTCAR"        # path of file containing the molecule atomic coordinates. The list of supported file types can be found on ASE website
    #E_slab_mol                         = [0.0, 0.0]            # slab and isolated molecule energies (in the default energy units of the DFT program, i.e. Ry for QE, eV for VASP).
    jobscript_path                      = "jobscript.sh"        # path of a jobscript for running Quantum Espresso
    #jobscript_ml_path                  = "jobscript_ml.sh"     # path of a jobscript for running the machine learning model
    submit_command                      = "sbatch"              # command for submitting the jobscript to the job scheduler
    #submit_command_ml                  = "sbatch"              # command executing or submitting the jobscript_ml
    #jobname_prefix                     = "ads"                 # prefix for the job names (max 3 letters, exceeding letters will be discarded)

[Structure]
    
    [Structure.adsorption_sites]
        mode                            = "high_symmetry"       # high_symmetry or coord_number
        surface_height                  = 0.9                   # delta_z from topmost atom defining the surface atoms for finding adsorption sites
        #selected_sites                 = [0, 1, 2]             # explicitly select the adsorption sites by index between those of the figure generated by running xsorb -sites

        [Structure.adsorption_sites.high_symmetry_params]
            symm_reduce                 = 0.01                  # tolerance for finding symmetrically inequivalent sites
            #near_reduce                = 0.01                  # tolerance for sites that are too close

        #[Structure.adsorption_sites.coord_number_params]
            #cn_method                  = "plain"               # method for finding coordination numbers: 'plain' (default, produces integer values), MinimumDistanceNN (Pymatgen, integer values), CrystalNN (Pymatgen)
            #range_selection            = {mode = "max", value = 4}  # if mode is 'max', select all sites with CN <= value, if mode is 'offset', select all sites with CN = min(CN) + value
            #include_surrounding_sites  = true                  # include also ontop sites of the atoms around the low CN ones.
            #surrounding_sites_deltaz   = 1.5                   # ontop sites for the neighbor atoms with z >= z_central_atom - surrounding_sites_deltaz will be included as surrounding sites
            #surrounding_exclude_main   = true                  # exclude the main sites (those selected by low CN criterion) from the surrounding sites (this can avoid duplicates)
            #atomic_species             = ["Cu", "Ni"]          # explicitly select only certain atomic species for the site selection
            #cn_plain_fixed_radius      = 1.5                   # fixed radius for the plain coordination number method (half of the max distance between two atoms to be considered nearest neighbors)

    [Structure.molecule]
        molecule_axis                   = {mode = "atom_indices", values = [3, 14]}  # indices of the two atoms to define the x-axis direction, or vector to take as x-axis, e.g. {mode = "vector", values = [1,0,0]}
        selected_atom_index             = 0                     # selected atom in molecule file, to be placed in all adsorption sites. If -1, use the center of mass of the molecule

        x_rot_angles                    = [0, 90, 180]          # rotation angles (in deg) about x axis (performed first)
        y_rot_angles                    = [0, 90]               # rotation about y axis (performed secondly)
        z_rot_angles                    = [0, 90]               # rotation about z axis (performed lastly)
        vertical_angles                 = "x"                   # which angles for y_rot +/- 90. Options: x (use x_rot_angles), z (use z_rot_angles), No (no rotations), list [list of angles] (custom list)
        #individual_rotations           = [[12, 50, 86], [1, 7, 8]]  # list of individual rotations, not to be included in the combinations. Each one should be a list of [x,y,z] angles (in deg)

        adsorption_distance_mode        = "value"               # options: 'value', 'covalent_radius', 'vdw_radius'
        target_distance                 = 2.0                   # DESIRED distance (in A) of the selected atom from the surface (z coord. above the topmost layer)
        min_distance                    = 1.5                   # minimum distance (in A) of ANY atom from surface, must be < selected_atom_distance. The molecule is translated upwards if necessary, in order to meet this requirement.

    #[Structure.constraints]
        #layers_height                  = 0.5                   # delta_z within which atoms are considered to be part of the same layer (for fixing atoms). This is different from the surface_height flag, used for surface adsorption sites.
        #fixed_layers_slab              = [0, 1, 2]             # fix chosen layers of the slab for relaxation (indices start from 0, corresponding to the bottom layer).
        #fixed_indices_slab             = [0, 1, 2, 3, 4, 5]    # fix chosen atoms of the slab for relaxation. Indices are to be taken as in slab file. -1 = fix all
        #fixed_indices_mol              = [3]                   # fix chosen atoms of the molecule for relaxation. Indices are to be taken as in slab file, possibly more than one site. -1 = fix all
        #fix_slab_xyz                   = [0, 0, 0]             # coordinates (x,y,z) to fix for the selected atoms in slab (as in QE, so 0 = fix)
        #fix_mol_xyz                    = [0, 0, 1]             # coordinates (x,y,z) to fix for the selected atoms in molecule
        #fix_bondlengths_preopt         = false                 # fix all bond lengths in the molecule in the preoptimization
        #fix_slab_preopt                = false                 # fix all slab atoms in the preoptimization (for now this is mutually exclusive with fix_bondlengths_preopt)

    #[Structure.misc]
        #mol_before_slab                = false                 # put molecule before slab in the order of atoms (only for xyz and pwi, not VASP)
        #sort_atoms_by_z                = true                  # sort atoms by z coordinate in the input files (only for xyz and pwi, not VASP)
        #translate_slab                 = true                  # translate the slab upwards so that the lowest atom is exactly 1 Angstrom above the cell bottom

[Calculation_parameters]
    dft_program                         = "VASP"                # VASP, QE

    [Calculation_parameters.dft_parameters]
        #VASP
        vasp_pp_path                    = "VASP_PP_PATH"        # The pseudopotentials are expected to be in: LDA: VASP_PP_PATH/potpaw/, PBE: VASP_PP_PATH/potpaw_PBE/, PW91: $VASP_PP_PATH/potpaw_GGA/
        #vasp_xc_functional             = "PBE"                 # default: PBE
        #vasp_pseudo_setups             = {"base": "recommended", "6": "C_h", "C": "_s"}  # for the default versions, just remove/comment this line
        #pymatgen_set                   = "MPRelaxSet"          # Use INCAR/KPOINTS preset from Pymatgen's sets
        #incar_path                     = "INCAR"               # path of the INCAR file
        #kpoints_path                   = "KPOINTS"             # path of the KPOINTS file
        ediffg_screening                = -0.5

        #QE
        #pwi_path = "template.pwi"  # path of the input file for Quantum Espresso (containing the settings, without the positions)
        #energy_conv_thr_screening      = 5e-3      # convergence threshold for energy
        #force_conv_thr_screening       = 5e-2      # convergence threshold for forces

