Input:
  slab_filename:                   ./slab/OUTCAR      #path of file containing the slab atomic coordinates. The list of supported file types can be found on ASE website
  molecule_filename:               ./mol/OUTCAR       #path of file containing the molecule atomic coordinates. The list of supported file types can be found on ASE website
  jobscript_path:                  jobscript.sh       #path of a jobscript for running Quantum Espresso
  submit_command:                  sbatch             #command for submitting the jobscript to the job scheduler


Structure:
  Adsoption_sites:
    
    mode:                          high_symmetry      #high_symmetry or coord_number
    surface_height:                0.9                #delta_z from topmost atom defining the surface atoms for finding adsorption sites
      

    high_symmetry_params:         
      symm_reduce:                 0.01               #tolerance for finding symmetrically inequivalent sites

  Molecule:
    molecule_axis:                 {mode: atom_indices, values: [3, 14]}  #indices of the two atoms to define the x-axis direction, or vector to take as x-axis, e.g. {mode: vector, values: [1,0,0]}
    selected_atom_index:           0                  #selected atom in molecule file, to be placed in all adsorption sites. If -1, use the center of mass of the molecule


    x_rot_angles:                  [0, 90, 180]       #rotation angles (in deg) about x axis (performed first)
    y_rot_angles:                  [0, 90]            #rotation about y axis (performed secondly)
    z_rot_angles:                  [0, 90]            #rotation about z axis (performed lastly)
    vertical_angles:               x                  #which angles for y_rot  +/- 90. Options: x (use x_rot_angles), z (use z_rot_angles), No (no rotations), list [list of angles] (custom list)

    adsorption_distance_mode:      value              #options: 'value', 'covalent_radius', 'vdw_radius'
    targed_distance:               2.0                #DESIRED distance (in A) of the selected atom from the surface (z coord. above the topmost layer)
    min_distance:                  1.5                #minimum distance (in A) of ANY atom from surface, must be < selected_atom_distance. The molecule is translated upwards if necessary, in order to meet this requirement.



Calculation_parameters:
  screening_conv_thr:              [-0.05]            #optional custom convergence treshold(s) for screening (2 values - energy and forces for QE, 1 value - energy OR force (EDIFFG) for VASP)

  DFT_code:                        VASP               #VASP, QE

  VASP_settings:
    vasp_pp_path:                  VASP_PP_PATH       #The pseudopotentials are expected to be in: LDA: VASP_PP_PATH/potpaw/,  PBE: VASP_PP_PATH/potpaw_PBE/,  PW91: $VASP_PP_PATH/potpaw_GGA/
