#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Fri 6 Feb 2023

@author: Enrico Pedretti
@author: Paolo Restuccia

Python script based on Pymatgen and ASE to build adatom adsorption on slabs calculated with Quantum ESPRESSO


# @Brief summary of the program:
# -Reads slab from file (many types supported, e.g. pwi/pwo, .xyz, .cif, POSCAR ...). The slab is assumed to be already relaxed.

# -Reads molecule from file. You must provide the indices of the two atoms that will define the x axis direction, or directly specify
#   the vector that will be taken as the x axis for the rotations.
#   It is also possible to select only a subset of the atoms by specifying the indices in the file. This can be useful to create fragments.

# -Finds all adsorption sites on the surface, optionally saves a .png with the identified sites.
#    If too many sites are identified, try to adjust (increase) the two threshold parameters 
#    'symm_reduce' and 'near_reduce' in the sites_find_args dictionary. 
#    Optionally you can also manually select the sites by specifying them with the indices plotted in the 
#    image generated with the option -sites. Note that by setting symm_reduce = 0 the program finds
#    ALL the high-symmetry sites, from which you can choose those that you want. 

# -Generates all the desired orientations of the molecule after translating to the origin the selected atom of the molecule, 
#    which will be later placed above the slab in the adsorption sites. 
#    NOTE: the selected atom index must be the one in the input file,
#    even if only a subset of the molecule is selected. The rotations are performed in the following order:
#    1) rotations along x axis ("screw")
#    2) rotations along y axis ("verticality": 0 = molecule horizontal, 90 = molecule vertical)
#    3) rotations along z axis (rotations in the horizontal plane)
#    
#    Optionally saves a .png with all the orientations viewed from above.

# -Generates configurations for all orientations placing the selected atom above all adsorption sites. Each configuration is labeled by an integer index.
#    In order to identify the labels, a table is written into a .csv containing label, xrot_angle, yrot_angle, z_rot_angle, site_type, x_site, y_site, z_site

# -Writes the .pwi for all the generated configurations and submits all the jobs in parallel for the scf screening.
#    Optionally it is possible to just generate the .pwi(s) without launching the jobs (useful for checking the generated
#    configurations before starting the calculations)
#    Optionally writes also the xsf files for visualization (so you can open them also with VESTA)

# -After the scf screening is completed, the scf energies can be extracted and are saved into a .csv

# -Finally, the configurations close to the energy minimum (within a threshold) calculated
#    with the scf screening can be relaxed to find the adsorption energies.

# -The parameters of the scripts (and of Espresso) must be set in the settings.in file, for which a template example
#    with all the mandatory and optional flags is provided.

"""

#Import statements#####################################################################
import numpy as np
from pymatgen.io import ase
from ase.io import read, write
import os, sys
#
import input
from espresso_mod import Espresso_mod
from slab import Slab, adsorb_both_surfaces
from molecule import Molecule
from io_utils import get_energies, get_z, launch_jobs, restart_jobs
########################################################################################

#TODO: sistemare la roba di magnetizzazione e potenziali, assicurarsi che gli indici corrispondano ai nomi.
#quindi non prenderli dalle input settings di espresso, ma nel primo blocco,
#usando un dizionario in modo che sia consistente coi nomi dei potenziali. Questo sia per starting_mag che per i vdw_coeffs


#TODO: check if 4-fold site is identified correctly (cerca materiale con sito 4-fold)
#TODO: job array?



def init():
    global pwi_prefix
    global pwo_prefix
    global scf_labels_filename
    global prerelax_labels_filename
    global scf_energies_filename
    global relax_energies_filename
    global slab_filename
    global molecule_filename
    global jobscript

    global script_settings_dict
    global espresso_settings_dict

    global E_slab_mol   
    global symm_reduce
    global near_reduce
    global slab_repeat
    global selected_sites
    global mol_subset_atoms
    global molecule_axis_atoms
    global axis_vector
    global selected_atom_index
    global selected_atom_distance
    global min_distance
    global x_rot_angles
    global y_rot_angles
    global z_rot_angles
    global no_rot_vert
    global fixed_indices_slab
    global fixed_layers_slab
    global fixed_indices_mol
    global fix_slab_xyz
    global fix_mol_xyz
    global kpoints
    global kpoints_offset
    global pseudopotentials
    global starting_mag
    global vdwg2_london_c6
    global vdwg2_london_rvdw
    global sites_find_args
    global ion_dynamics


    #preset variables:######################################################################
    #output paths
    pwi_prefix               = 'input'  #prefix: the files will be named pwi_prefix_i.pwi with i=1,2,...
    pwo_prefix               = 'output'
    scf_labels_filename      = 'scf_site_labels.csv'
    prerelax_labels_filename = 'prerelax_site_labels.csv'
    scf_energies_filename    = 'scf_energies.csv'
    relax_energies_filename  = 'finalrelax_energies.csv'
    #########################################################################################


    #user settings variables################################################################
    script_settings_dict, espresso_settings_dict = input.read_input_file("settings.in")

    #check for existence of the four blocks
    blocks = ['INPUT','STRUCTURE','CALCULATION','PSEUDO']
    for block in blocks:
        if block not in script_settings_dict:
            print("'"+block+"' block not found in settings.in.")
            sys.exit(1)

    #check existence of mandatory variables in blocks
    mandatory_flags_list = [
        ['slab_filename','molecule_filename', 'jobscript'], 
        ['selected_atom_index', 'x_rot_angles', 'y_rot_angles', 'z_rot_angles'], 
        ['kpoints']
        ]
    for block in script_settings_dict:
        i = -1
        if   block=='INPUT': i=0
        elif block=='STRUCTURE': i=1
        elif block=='CALCULATION': i=2
        elif block=='PSEUDO': continue
        for flag in mandatory_flags_list[i]:
            if flag not in script_settings_dict[block]:
                print("Mandatory flag '"+flag + "' not found in settings.in.")
                sys.exit(1)

    if 'molecule_axis_atoms' in script_settings_dict['STRUCTURE'] and 'axis_vector' in script_settings_dict['STRUCTURE']:
        print("You can specify the molecule axis either by 'molecule_axis_atoms' or 'axis_vector', not both.")
        sys.exit(1)
    if 'fixed_indices_slab' in script_settings_dict['STRUCTURE'] and 'fixed_layers_slab' in script_settings_dict['STRUCTURE']:
        print("You can specify the fixed slab atoms either by 'fixed_indices_slab' or 'fixed_layers_slab', not both.")
        sys.exit(1)


    #set non-specified flags to default.
    optional_flags_list = {
        'symm_reduce'              : 0.01,
        'near_reduce'              : 0.01,
        'selected_sites'           : ' ',
        'slab_repeat'              : '1 1 1',
        'mol_subset_atoms'         : ' ',
        'molecule_axis_atoms'      : ' ',
        'axis_vector'              : ' ',
        'selected_atom_distance'   : 2.0,
        'min_distance'             : 1.0,
        'no_rot_vert'              : '.true.',
        'fixed_indices_slab'       : ' ',
        'fixed_layers_slab'        : ' ',
        'fixed_indices_mol'        : ' ',
        'fix_slab_xyz'             : '0 0 1',
        'fix_mol_xyz'              : '0 0 1',
    }
    for flag in optional_flags_list:
        if flag not in script_settings_dict['STRUCTURE']:
            script_settings_dict['STRUCTURE'].update({flag : optional_flags_list[flag]})
    if 'ion_dynamics' not in espresso_settings_dict['IONS']:
        espresso_settings_dict['IONS'].update({'ion_dynamics': 'bfgs'})
    if 'kpoints_offset' not in script_settings_dict['CALCULATION']:
        script_settings_dict['CALCULATION'].update({'kpoints_offset': '0 0 0'})


    #Finally read data from dictionary and initialize the actual variables

    #&INPUT:
    slab_filename          = script_settings_dict['INPUT']['slab_filename']
    molecule_filename      = script_settings_dict['INPUT']['molecule_filename']
    jobscript              = script_settings_dict['INPUT']['jobscript']
    E_slab_mol             = np.array(script_settings_dict['INPUT']['E_slab_mol'].split(), dtype=float).tolist() if 'E_slab_mol' in script_settings_dict['INPUT'] else []
    if len(E_slab_mol) != 2 and len(E_slab_mol) != 0:
        print("If you specify the tag E_slab_mol you must provide TWO values.")
        sys.exit(1)


    #&STRUCTURE
    symm_reduce            = float(script_settings_dict['STRUCTURE']['symm_reduce'])
    near_reduce            = float(script_settings_dict['STRUCTURE']['near_reduce'])
    selected_sites         = np.array(script_settings_dict['STRUCTURE']['selected_sites'].split(), dtype=int).tolist()
    slab_repeat            = np.array(script_settings_dict['STRUCTURE']['slab_repeat'].split(), dtype=int).tolist()

    mol_subset_atoms       = np.array(script_settings_dict['STRUCTURE']['mol_subset_atoms'].split(), dtype=int).tolist()
    molecule_axis_atoms    = np.array(script_settings_dict['STRUCTURE']['molecule_axis_atoms'].split(), dtype=int).tolist()
    axis_vector            = np.array(script_settings_dict['STRUCTURE']['axis_vector'].split(), dtype=float).tolist()
    selected_atom_index    = int(script_settings_dict['STRUCTURE']['selected_atom_index'])
    selected_atom_distance = float(script_settings_dict['STRUCTURE']['selected_atom_distance'])
    min_distance           = float(script_settings_dict['STRUCTURE']['min_distance'])           
    x_rot_angles           = np.array(script_settings_dict['STRUCTURE']['x_rot_angles'].split(), dtype=float).tolist()
    y_rot_angles           = np.array(script_settings_dict['STRUCTURE']['y_rot_angles'].split(), dtype=float).tolist()  
    z_rot_angles           = np.array(script_settings_dict['STRUCTURE']['z_rot_angles'].split(), dtype=float).tolist()          
    no_rot_vert            = True if 'true' in script_settings_dict['STRUCTURE']['no_rot_vert'].lower() else False

    fixed_indices_slab     = np.array(script_settings_dict['STRUCTURE']['fixed_indices_slab'].split(), dtype=int).tolist()
    fixed_layers_slab      = np.array(script_settings_dict['STRUCTURE']['fixed_layers_slab'].split(), dtype=int).tolist()
    fixed_indices_mol      = np.array(script_settings_dict['STRUCTURE']['fixed_indices_mol'].split(), dtype=int).tolist()
    fix_slab_xyz           = np.array(script_settings_dict['STRUCTURE']['fix_slab_xyz'].split(), dtype=int).tolist() 
    fix_mol_xyz            = np.array(script_settings_dict['STRUCTURE']['fix_mol_xyz'].split(), dtype=int).tolist()



    #&CALCULATION
    kpoints                = np.array(script_settings_dict['CALCULATION']['kpoints'].split(), dtype=int).tolist() if 'gamma' not in script_settings_dict['CALCULATION']['kpoints'].lower() else None
    kpoints_offset         = np.array(script_settings_dict['CALCULATION']['kpoints_offset'].split(), dtype=int).tolist()

    #&PSEUDO
    pseudopotentials       = script_settings_dict['PSEUDO']

    #Espresso &SYSTEM (correction to bugs in ase function to write pwis)
    starting_mag = []
    vdwg2_london_c6 = []
    vdwg2_london_rvdw = []
    keys_to_be_removed = []
    for i, species in enumerate(pseudopotentials):
        for key in espresso_settings_dict['SYSTEM']:
            if 'starting_magnetization' in key:
                if i == int(key.split('(')[1].split(')')[0]):
                    starting_mag.append(espresso_settings_dict['SYSTEM'][key])
                    keys_to_be_removed.append(key)
            if 'london_c6' in key:
                if i == int(key.split('(')[1].split(')')[0]):
                    vdwg2_london_c6.append(espresso_settings_dict['SYSTEM'][key])
                    keys_to_be_removed.append(key)
            if 'london_rvdw' in key:
                if i == int(key.split('(')[1].split(')')[0]):
                    vdwg2_london_rvdw.append(espresso_settings_dict['SYSTEM'][key])
                    keys_to_be_removed.append(key)
        if(len(starting_mag) < i): starting_mag.append(None)
        if(len(vdwg2_london_c6) < i): vdwg2_london_c6.append(None)
        if(len(vdwg2_london_rvdw) < i): vdwg2_london_rvdw.append(None)


    for key in keys_to_be_removed:
        espresso_settings_dict['SYSTEM'].pop(key)

    #Espresso &IONS
    ion_dynamics = espresso_settings_dict['IONS']['ion_dynamics']

    sites_find_args = {
        "distance":0,   #the distance isn't set from here, but inside the molecule, by translating the mol upwards by the chosen amount
        'symm_reduce':symm_reduce, 
        'near_reduce':near_reduce, 
        'no_obtuse_hollow':True}
############################################################################################################


def plot_adsorption_sites():
    print('\nLoading slab...')
    slab = Slab(slab_filename)
    print('Slab loaded.')

    print('Finding adsorption sites...')
    slab.find_adsorption_sites(* {
        "distance":0, 
        'symm_reduce':symm_reduce, 
        'near_reduce':near_reduce, 
        'no_obtuse_hollow':True}.values(),
         save_image=True)
    print('Adsorption sites found.')

def generate(SCF_RUN : bool, SAVEFIG=True, WRITE_XSF=False): 
 
    #BEGIN STRUCTURES GENERATION ############################################################################

    #Slab import from file
    print('\nLoading slab...')
    slab = Slab(slab_filename)
    print('Slab loaded.')

    #sga = SpacegroupAnalyzer(slab.slab_pymat)
    #sops = sga.get_point_group_operations(cartesian=True)
    #for sop in sops:
    #    if sop.rotation_matrix[2][2] == 1.:
    #        print(sop.rotation_matrix)


    #Molecule import from file
    print('Loading molecule...')
    mol = Molecule(molecule_filename, molecule_axis_atoms, axis_vector, mol_subset_atoms)
    print('Molecule loaded.')


    #Find adsorption sites and labels (site type and x,y coords.)
    print('Finding adsorption sites...')
    adsites, adsites_labels = slab.find_adsorption_sites(
        *sites_find_args.values(), 
        save_image=SAVEFIG,
        selected_sites=selected_sites)
    print('Adsorption sites found.')


    if os.path.isfile(pwo_prefix+'_prerelax_0.pwo'): #if the pre-relaxed files are present, read distance from there, else use the user-defined value
        i = 0
        distances_from_surf = []
        while(True):
            if os.path.isfile(pwo_prefix+'_prerelax_{0}.pwo'.format(i)):
                atom_index = selected_atom_index + len(slab.slab_pymat.sites)
                distances_from_surf.append(get_z(pwo_prefix+'_prerelax_{0}.pwo'.format(i), atom_index) - max(slab.slab_ase.positions[:,2]) )
                i = i+1
            else: break
        print("Prerelaxations found. Default distances will be read from there.")
    else:
        distances_from_surf = len(x_rot_angles)*[selected_atom_distance]


    #Generate all the configs for the various molecular rotations and a list of labels
    print('Generating molecular configurations...')
    all_mol_configs_pymat, configs_labels = mol.generate_molecule_rotations(
        atom_index=selected_atom_index,  
        vert_rotations=y_rot_angles,
        screw_rotations=x_rot_angles, 
        horiz_rotations=z_rot_angles, 
        no_vert_rotx=no_rot_vert,
        distance_from_surf=distances_from_surf, 
        min_distance=min_distance, 
        save_image=SAVEFIG
        )
    print('All molecular configurations generated.')


    #Adsorption of molecule on all adsorption sites for all molecule orientations  
    print('Generating adsorption structures...')
    all_mol_on_slab_configs_pymat = [slab.generate_adsorption_structures(molecule=mol_config, adsites=adsites, repeat=slab_repeat, translate=False, reorient=False) for mol_config in all_mol_configs_pymat]
    all_mol_on_slab_configs_pymat = sum(all_mol_on_slab_configs_pymat, []) #flatten the 2D array
    if(False): all_mol_on_slab_configs_pymat = adsorb_both_surfaces(all_mol_on_slab_configs_pymat) #Replicate molecule on the other side of the slab. NOTE: Currently not working!
    all_mol_on_slab_configs_ase = [ase.AseAtomsAdaptor.get_atoms(config) for config in all_mol_on_slab_configs_pymat]
    full_labels = [mol_config[0]+site_label+mol_config[1] for mol_config in configs_labels for site_label in adsites_labels]
    print('All slab+adsorbate cells generated.')

        
    print('Writing pwi(s)...')
    csvfile=open(scf_labels_filename, 'w')
    csvfile.write('Label' + ',' + 'xrot' + ',' + 'yrot' + ',' + 'zrot' + ',' + 'site' + ',' + 'x' + ',' + 'y' + ',' + 'z' +'\n')

    if SCF_RUN or 'calculation' not in espresso_settings_dict['CONTROL']: 
        espresso_settings_dict['CONTROL'].update({'calculation' : 'scf'})
    espresso_settings_dict['CONTROL'].update({'restart_mode' : 'from_scratch'})

    
    pwi_names = []

    for i in np.arange(len(all_mol_on_slab_configs_ase)):
        name_file = pwi_prefix+'_scf_'+str(i)
        pwi_names.append(name_file+'.pwi')
        calc = Espresso_mod(pseudopotentials=pseudopotentials, 
                    input_data=espresso_settings_dict,
                    label=name_file,
                    kpts=kpoints,koffset=kpoints_offset)
        if(fixed_layers_slab): 
            fixed_slab = slab.get_atoms_by_layers(fixed_layers_slab)
        else: fixed_slab = fixed_indices_slab
        calc.set_fixed_atoms(fixed_slab, slab.reindex_map, fixed_indices_mol, mol.reindex_map, len(slab.slab_pymat.sites), len(mol.mol_pymat.sites), fix_slab_xyz, fix_mol_xyz)
        calc.set_starting_magnetizations(starting_mag)
        calc.set_vdwd2_coeffs(vdwg2_london_c6, vdwg2_london_rvdw)
        calc.write_input(all_mol_on_slab_configs_ase[i])
        if(WRITE_XSF): write(name_file+'.xsf', all_mol_on_slab_configs_ase[i])

        csvfile.write(str(i)+','+full_labels[i]+'\n')

    csvfile.close()

    print('All pwi(s) written.')
    #END OF STRUCTURE GENERATIONS #########################################################################################
    
    if SCF_RUN:
        launch_jobs(jobscript=jobscript, pwi_list=pwi_names, outdirs='scf_outdirs', jobname_prefix='scf', pwi_prefix=pwi_prefix, pwo_prefix=pwo_prefix)

def pre_relax(WRITE_XSF : bool =False):
  
   #BEGIN OF STRUCTURES GENERATION ############################################################################

    #Slab import from file
    print('\nLoading slab...')
    slab = Slab(slab_filename)
    print('Slab loaded.')

    #Molecule import from file
    print('Loading molecule...')
    mol = Molecule(molecule_filename, molecule_axis_atoms, axis_vector, mol_subset_atoms)
    print('Molecule loaded.')

    #Find adsorption sites and labels (site type and x,y coords.)
    print('Finding adsorption sites...')
    adsites, adsites_labels = slab.find_adsorption_sites(*sites_find_args.values(), save_image=False)
    print('Adsorption sites found.')

    x = ['ontop' in i for i in adsites_labels]
    ontop_index = x[0]

    #Generate all the configs for the various molecular rotations and a list of labels
    print('Generating molecular configurations...')
    all_mol_configs_pymat, configs_labels = mol.generate_molecule_rotations(
        atom_index=selected_atom_index,  
        vert_rotations=y_rot_angles,
        screw_rotations=x_rot_angles, 
        horiz_rotations=[0], 
        no_vert_rotx=False,
        distance_from_surf=selected_atom_distance, 
        min_distance=min_distance, 
        save_image=False
        )
    print('All molecular configurations generated.')


    #generate_adsorption_structures
    #Adsorption of molecule only on a top site for z relaxation
    print('Generating adsorption structures...') 
    adsites_labels = [[ads for ads in adsites_labels if 'top' in ads][0]]
    all_mol_on_slab_configs_pymat = [slab.generate_adsorption_structures(molecule=mol_config, adsites=[adsites[ontop_index]], repeat=slab_repeat, translate=False, reorient=False) for mol_config in all_mol_configs_pymat]
    all_mol_on_slab_configs_pymat = sum(all_mol_on_slab_configs_pymat, []) #flatten the 2D array
    if(False): all_mol_on_slab_configs_pymat = adsorb_both_surfaces(all_mol_on_slab_configs_pymat) #Replicate molecule on the other side of the slab. NOTE: Currently not working!
    all_mol_on_slab_configs_ase = [ase.AseAtomsAdaptor.get_atoms(config) for config in all_mol_on_slab_configs_pymat]

    full_labels = [mol_config[0]+site_label+mol_config[1] for mol_config in configs_labels for site_label in adsites_labels]
    print('Slab+adsorbate cells for the top sites generated.')

        
    csvfile=open(prerelax_labels_filename, 'w')
    csvfile.write('Label' + ',' + 'xrot' + ',' + 'yrot' + ',' + 'zrot' + ',' + 'site' + ',' + 'x' + ',' + 'y' + ',' + 'z' +'\n')

    espresso_settings_dict['CONTROL'].update({'calculation' : 'relax'})
    espresso_settings_dict['CONTROL'].update({'restart_mode' : 'from_scratch'})
    espresso_settings_dict['IONS'].update({'ion_dynamics': ion_dynamics})

    pwi_names = []
    for i in np.arange(len(all_mol_on_slab_configs_ase)):
        name_file = pwi_prefix+'_prerelax_'+str(i)
        pwi_names.append(name_file+'.pwi')
        calc = Espresso_mod(pseudopotentials=pseudopotentials, 
                    input_data=espresso_settings_dict,
                    label=name_file,
                    kpts=kpoints,koffset=kpoints_offset)

        #all_slab_fixed = list(range(len(slab.slab_pymat.sites)))
        #all_mol_fixed = np.array(list(range(len(mol.mol_pymat.sites)))) + len(slab.slab_pymat.sites)
        calc.set_fixed_atoms([-1], slab.reindex_map, [-1], mol.reindex_map, len(slab.slab_pymat.sites), len(mol.mol_pymat.sites) , [0, 0, 0], [0, 0, 1])
        calc.set_starting_magnetizations(starting_mag)
        calc.set_vdwd2_coeffs(vdwg2_london_c6, vdwg2_london_rvdw)
        calc.write_input(all_mol_on_slab_configs_ase[i]) 
        if(WRITE_XSF): write(name_file+'.xsf', all_mol_on_slab_configs_ase[i])      

        csvfile.write(str(i)+','+full_labels[i]+'\n')

    csvfile.close()

    launch_jobs(jobscript=jobscript, pwi_list=pwi_names, outdirs='prerelax_outdirs', jobname_prefix='p_rel', pwi_prefix=pwi_prefix, pwo_prefix=pwo_prefix)

def final_relax(threshold : float = None, exclude : list[int] = []):

    #Slab import from file
    print('\nLoading slab...')
    slab = Slab(slab_filename)
    print('Slab loaded.')

    #Molecule import from file
    print('Loading molecule...')
    mol = Molecule(molecule_filename, molecule_axis_atoms, axis_vector, mol_subset_atoms)
    print('Molecule loaded.')
    
    print('Collecting energies from scf screening...')
    energies = get_energies(scf_labels_filename, scf_energies_filename, E_slab_mol=E_slab_mol, pwo_prefix=pwo_prefix+'_scf')
    if None in energies:
        print('Not all the calculations have reached convergence. Cannot run the final calculation.')
        sys.exit(1)
    print('Scf energies collected.')
    

    e_min = min([energies[i] for i in [*range(len(energies))] if i not in exclude])
    i_minimum = energies.index(e_min)
    calcs = []
    subset_energies = []
    if threshold is not None:
        for i, energy in enumerate(energies):
            if i in exclude: continue
            if energy - e_min <= threshold:
                calcs.append(i)
                subset_energies.append(energy)
        #sort them by minimum energy, in order to launch first the minimum
        sorted_indices = np.argsort(subset_energies, kind='stable').tolist()
        calcs = [calcs[i] for i in sorted_indices]
    else: calcs = [i_minimum]


    espresso_settings_dict['CONTROL'].update({'calculation' : 'relax'})
    espresso_settings_dict['CONTROL'].update({'restart_mode' : 'from_scratch'})
    espresso_settings_dict['IONS'].update({'ion_dynamics': ion_dynamics})

    pwi_names = []
    for i in calcs:       
        struct_ase = read(pwi_prefix+'_scf_'+str(i)+'.pwi') #simply reads the files, avoid to re-generate them

        fixed_indices_molecule = len(read(slab_filename)) + np.array(fixed_indices_mol)

        pwi_name = pwi_prefix+'_finalrelax_'+str(i)
        pwi_names.append(pwi_name+'.pwi')
        calc = Espresso_mod(pseudopotentials=pseudopotentials, 
                    input_data=espresso_settings_dict,
                    label=pwi_name,
                    kpts=kpoints,
                    koffset=kpoints_offset)
        if(fixed_layers_slab): fixed_slab = slab.get_atoms_by_layers(fixed_layers_slab)
        else: fixed_slab = fixed_indices_slab
        calc.set_fixed_atoms(
            fixed_slab,
            slab.reindex_map, 
            fixed_indices_molecule,
            mol.reindex_map, 
            len(slab.slab_pymat.sites), 
            len(mol.mol_pymat.sites),
            fix_slab_xyz, fix_mol_xyz)
        calc.set_starting_magnetizations(starting_mag)
        calc.set_vdwd2_coeffs(vdwg2_london_c6, vdwg2_london_rvdw)
        calc.write_input(struct_ase)

    launch_jobs(jobscript=jobscript, pwi_list=pwi_names, outdirs='finalrelax_outdirs', jobname_prefix='f_rel', pwi_prefix=pwi_prefix, pwo_prefix=pwo_prefix)


def main():

    if(len(sys.argv) == 1):
        print('You need to specify at least one option. Quitting.')
        return 1

    if('--h' in sys.argv or '--help' in sys.argv or '-h' in sys.argv):
        print('Options:')
        print('-sites            plot the identified high-symmetry sites sites with labels')
        print('-pr               prerelax molecule along z for the different x rotations (only for the ontop site)')
        print('-g                generate all pwi(s) and csv with labels, without submitting the jobs')        
        print('-s                launch scf screening')
        print('-es               get scf energies')
        print('-fr               launch final relaxations')
        print('-ef               get final relaxed energies')
        print('Additional flags:')
        print('--fig             plot also the figures (sites + molecule orientations) when launching scf screening')
        print('--xsf             generate also xsf files besides the pwi(s)')
        print('--t value         energy threshold above minimum (in eV) for choosing the configurations for the final relaxation')
        print('--exclude [0,3,4] exclude selected configurations from the final relaxation ')
        print('--restart         restart calculation (can also be abbreviated as --res)')
        return 0

    if('-sites' not in sys.argv and '-g' not in sys.argv and '-pr' not in sys.argv and '-s' not in sys.argv and '-es' not in sys.argv and '-fr' not in sys.argv and '-ef' not in sys.argv):
        print('You need to specify at least one option (-sites, -g, -pr, -s, -es, -fr, -ef). Quitting.')
        return 1

    init()

    SAVEFIG   = '--fig' in sys.argv
    WRITE_XSF = '--xsf' in sys.argv
    
    if('-sites' in sys.argv):
        plot_adsorption_sites()
    
    elif('-g' in sys.argv or '-s' in sys.argv):
        if '-s' in sys.argv and ('--restart' in sys.argv or '--res' in sys.argv): restart_jobs(jobscript=jobscript, which='scf', pwi_prefix=pwi_prefix, pwo_prefix=pwo_prefix)
        else: generate(SCF_RUN = '-s' in sys.argv, SAVEFIG=SAVEFIG, WRITE_XSF=WRITE_XSF)

    elif('-pr' in sys.argv):
        if '--restart' in sys.argv or '--res' in sys.argv:
            restart_jobs(jobscript=jobscript, which="prerelax", pwi_prefix=pwi_prefix, pwo_prefix=pwo_prefix)
        else:
            pre_relax(WRITE_XSF=WRITE_XSF)

    elif('-es' in sys.argv):
        get_energies(scf_labels_filename, scf_energies_filename, E_slab_mol=E_slab_mol, pwo_prefix=pwo_prefix+'_scf')

    elif('-fr' in sys.argv):
        if '--restart' in sys.argv or '--res' in sys.argv: restart_jobs(jobscript=jobscript, which="finalrelax", pwi_prefix=pwi_prefix, pwo_prefix=pwo_prefix)
        else:
            threshold = None
            exclude = []
            if '--exclude' in sys.argv:
                exclude = [int(i) for i in (sys.argv[sys.argv.index('--exclude')+1].split('[')[1].split(']')[0].split(','))]
                print('Configurations {0} will be excluded, as requested'.format(exclude))
            if('--t' in sys.argv):
                if(len(sys.argv)> sys.argv.index('--t')+1):
                    threshold = sys.argv[sys.argv.index('--t')+1]
                    if not input._is_number(threshold):
                        print('The value after --t must be a number. Quitting.')
                        return 1 
                    threshold = float(threshold)             
                else:
                    print('You need to specify a value after --t. Quitting.')
                    return 1
            final_relax(threshold, exclude=exclude)

    elif('-ef' in sys.argv): #read final energies
        if not os.path.isfile(scf_energies_filename):
            get_energies(scf_labels_filename, scf_energies_filename, E_slab_mol=E_slab_mol, pwo_prefix=pwo_prefix+'_scf')
            get_energies(scf_energies_filename, relax_energies_filename, E_slab_mol=E_slab_mol, pwo_prefix=pwo_prefix+'_finalrelax')
            os.remove(scf_energies_filename)
        else:    
            get_energies(scf_energies_filename, relax_energies_filename, E_slab_mol=E_slab_mol, pwo_prefix=pwo_prefix+'_finalrelax')


if __name__ == '__main__':
    sys.exit(main())
