name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint ase==3.22.1 pymatgen==2023.3.23 matplotlib>=3.7.1 numpy>=1.24.2 pandas>=2.0.0
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
